#!/usr/bin/fish
set -g tempfile 

set -g rpm (jq '.["amdgpu-pci-0100"].fan1.fan1_input' (sensors -j | psub))
set -g temp (jq '.["amdgpu-pci-0100"].edge.temp1_input' (sensors -j | psub))

if test $status -ne 0
    echo " ERROR"
else
    echo " RX 580: $temp°C, $rpm RPM"
end
