#!/usr/bin/fish

set keyboard_identifier "1008:2447:HP,_Inc_HyperX_Alloy_Origins_Core"
# set current_layout_string (command swaymsg -t get_inputs | jq '.[] | select(.identifier=="'$keyboard_identifier'").xkb_active_layout_name')
set current_layout_string (command swaymsg -t get_inputs | jq -r ".[] | select((.identifier==\"$keyboard_identifier\") and (.type==\"keyboard\")).xkb_active_layout_name")

echo " $current_layout_string"
