#!/usr/bin/fish

# save the top $TOTAL_TRACKS listened to on spotify from the past 4 weeks into a designated directory in a new plaintext file with the filename being the current date
# idea is to run this script once every 2 weeks via a cron job (or systemd timer or similar)

set -g TOTAL_TRACKS $argv[1]
set -g URL "https://api.spotify.com/v1/me/top/tracks?limit=$TOTAL_TRACKS&time_range=short_term"
set -g AUTHORIZATION "Authorization: Bearer BQCeBUE0GPwRvClPcYLIT1xsS-XyBeLuGiOw4XO6BAtuChNP0f7mVu5jeHJDGcb11R3dMirqGCxYTMQ6LeHvM-AmvSTThKO4DjofbOTxdm0XF2bM3FjHk-VkQkIe1mVk9Ps_Xft5ZZEA99SHQXF5lPSzIFSigMnneylV1mMjVHcnFg_80DK7rOAV9vws-jG1MMW4JFq9AJQ_lDxdRSiYESf_"
set -g SAVE_DIR "$HOME/spotify_top_last4weeks"
set -g NEW_FILENAME (date '+%d-%m-%Y')

set DATA (curl -X GET $URL -H $AUTHORIZATION)

for i in (seq 0 (math $TOTAL_TRACKS - 1))
    echo (math $i + 1). (jq .items[$i].artists[0].name (echo -n $DATA | psub)) - (jq .items[$i].name (echo -n $DATA | psub)) >> "$SAVE_DIR/$NEW_FILENAME"
end
